### ISSUE TITLE
Allow opening links in a new tab

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1217]
A navigation button or anything else that changes the route should allow to also open this in a new tab (through right click and select or `ctrl` + right click). Currently this options is not supported:

![image](https://user-images.githubusercontent.com/33730997/164680109-ed132a76-0962-4fab-b7dc-c370591013d0.png)

I am not fully sure what is required in order to tell the browser that this is a navigation link. It might need a `href` link on the anchor (`<a>`) element. 

It would be great to have this functionality as with #1047 it would be possible to quickly open new tabs without having to login again.

**Comment by sleidig** [comment]
we should also carefully test whether there are risks of errors or data inconsistencies when running two tabs in parallel

**Comment by sleidig** [comment]
Adding `<a href` (which adds options to open in tab) breaks the in-app navigation (page always is reloaded then). So that is not feasible at the moment.
Opening in tabs may also create unexpected behavior if the app is installed as a PWA without browser UI.

Adding "copy to clipboard" option to the Shortcut Widget as a utility now.

We might completely overwrite the context menu some time in the future (if that is possible in our structure).
