### ISSUE TITLE
improve dataType architecture

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1920]
There are a few challenges with the current architecture around our dataType definitions and the schemaField configurations. This issue is a collection of issues and ideas for this area.

### Issues
- Array types not easy to identify (e.g. “entity-array” -> is also array)
- entity and configurable enum use additional / innerDatatype inconsistently (especially as arrays)
- Multiple “date” datatypes with lots of common logic (filter, parsing, …)

### Possible improvements
- “isArray” property on schemaFields ?
- inheritance between related dataTypes
- registration of dataTypes via multi-provider in DI
  - to simplify the decentralised registration of new types (e.g. ConfigurableEnumModule registering that dataType)
  - makes DI available to be used in dataTypes (more power for transformations + simpler method signatures for `transformToDatabaseFormat`)

**Comment by TheSlimvReal** [comment]
The DI approach is not super straight forward as we would like to inject the `EntitySchemaService` in the data types but the `EntitySchemaService` depends on the data types which then creates a cyclic dependency. 
This is currently not an issue because the schema service is only used later but if we want to use DI this creates a problem.
The only approach I could come up with is to only later inject the data types in the `EntitySchemaService` using the `Injector`.
