### ISSUE TITLE
label not persist in data structure edit mode

### ISSUE THREAD

**Issue by tomwwinter** [Aam-Digital/ndb-core#2183]
**Describe the bug**
Manipulated entities in structure edit view does not persist correctly. The position is saved correctly, but the edited label field resets.

**To Reproduce**
1. Go to https://cc.aam-digital.net/child/1
2. Click on `edit data structure`
3. Move `name` field to another group and change the label
4. Click save.
5. See error: name field moved to new group, but not updated the label

**Expected behavior**
Label should also be saved correctly

**Additional context**
Not happening on the PR deployment so it seems to have to do with having a real DB.

**Comment by sleidig** [comment]
It turns out that this is an incompatibility of the new config format. Most instances are using the old array-based entity.attributes. To correctly save and persist changes, the new object-based config for entities is required.

I suggest we run a server-side migration now. The latest app version can handle both config formats, so this should not be noticeable to users. #2066

**Comment by sleidig** [comment]
Config formats have been migrated and updated in CouchDBs now, using ndb-admin API. This bug is thereby fixed.
