### ISSUE TITLE
Refactor getNotesOfChild to EntityMapper

### ISSUE THREAD

**Issue by codingfabi** [Aam-Digital/ndb-core#221]
I wanted to implement a function to get all Health Checks for a certain loaded child.
I wanted to do it familiar to the way we load notes of a child into the ChildDetailComponent. 
But i dont know how to implement a index in pouchDB that i can query. 

We should refactor and rethink the following:

```
 getNotesOfChild(childId: string): Observable<Note[]> {
    const promise = this.db.query('notes_index/by_child', {key: childId, include_docs: true})
      .then(loadedEntities => {
        return loadedEntities.rows.map(loadedRecord => {
          const entity = new Note('');
          entity.load(loadedRecord.doc);
          return entity;
        });
      });

    return Observable.fromPromise(promise);
  }

```
In my opinion, this belongs into the Entity Mapper and should be made generic.

**Comment by liwde** [comment]
https://pouchdb.com/guides/queries.html

These indices affect two separate use cases:
1. Statistics
2. Traversing relations between entities

I'm fine with statistics not being part of the EntityMapper, but traversing relations is a general problem: Health Checks, Notes, ChildSchoolRelationships, ...

Shouln't the Entity to be queried by provide the map-function?

```ts
export class Note extends Entity {
  static ENTITY_TYPE = 'Note';
  static dbViews : any = [/* All Design Docs relevant for the Entity */]
}
```

The EntityMapper may then be queried like this:

```ts
this._entityMapper.getRelational<Child, Note>(childId);
```

At the point, this method is called, the EntityMapper should make sure that for both Child and Note the dbViews have been added to PouchDB and use the right index to execute the Query and construct the Entities.

(There needs to be put some more thought into having metadata for the dbViews so that the EntityMapper can pick the correct one, but this seems like a solution to me)

**Comment by liwde** [comment]
@TheSlimvReal How did you implement this for the ChildSchoolRelations?

**Comment by sleidig** [comment]
The idea behind our architecture of `Entity` and `EntityMapper` is the [Data Mapper pattern](https://martinfowler.com/eaaCatalog/dataMapper.html), i.e. to keep the Entity class/classes free of any database related concerns and simply focus on the "business logic" in them.

Therefore, I would try to put that stuff into `EntityMapper` (originally, the idea was also to implement subclasses of EntityMapper for different Entity type, e.g. a `ChildMapper`. But so far there was no real use for it).

The index for Notes is triggered in the constructor of `ChildrenService`: https://github.com/NGO-DB/ndb-core/blob/67aad641c397fe130f8d58dec1975a90fc3ffc8d/src/app/children/children.service.ts#L163-L177
For now, you could add another similar function there. But the whole `ChildrenService` class is becoming a mess of duplicate code. We definitely need a generic system to replace all that.
