### ISSUE TITLE
Click mode `navigate` does not work in `RelatedTimePeriodEntities`

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#2210]
**Describe the bug**
When clicking the "+" button in a panel table with click mode `navigate` (e.g. `RelatedTimePeriodEntitiesComponent`) the user is directed to a invalid route.

**Expected behavior**
The user should be directed to the route `.../new`

**Additional context**
This happens because the `newRecordFactory` is used to create a new record and then clicking the "+" button redirects to the ID of the provided entity. As in this case the entity has not been saved yet, the user should be instead directed to new.
A simple check for the `isNew` property would probably be sufficient.

**Comment by sleidig** [comment]
I think we can currently not really support this case (navigate instead of popup for a new entity from related-entities-table), because the simple /new routed form will not hold any of the necessary relation reference. I would discourage a setup using navigation here, because I would expect that this almost certainly leads to confusion and data loss for users.

I guess we use this in codo setups? ...

Possible we can consider passing a new, unsaved entity to a routed view somehow, when reworking the popup vs fullscreen architecture to be more aligned (#2069)
