### ISSUE TITLE
using pouchdb-authentication with user administration

### ISSUE THREAD

**Issue by codingfabi** [Aam-Digital/ndb-core#272]
So during working on #254 with PR #271, I stumbled across the pouchdb-authentication API that we already use in the pouch-database-manager-service and i wanted to use it for the user-administration aswell because it provides good services for changing passwords and creating users etc. But here's why we cant use it right now: 

pouchdb-authentication expects users as normal json objects within the _users in the Database, but our users for the application are stored differently, as normal json objects with the id "User:Username" as we treat them as subtypes of entity. 
My question now is, can we make pouchdb-authentication work somehow by refactoring the user concept and somehow using the _users? because changing passwords without a API could be pretty painfull...
@liwde are there some changes coming with the new session that you are implementing?

**Comment by sleidig** [comment]
The initial design of the `User` Entity (as simple data objects comparable to our other Aam Digital entities like `Child` or `School`) side by side with CouchDB's user objects in its dedicated `_users` database was based on my wrong assumption that the _users database would not be synced and available offline. As offline login was a requirement, the easy solution seemed to design a user/authentication system inside Aam Digital that is independent of the CouchDB user accounts.

This has actually led to a few issues, especially around changing passwords (#17) - because that needs to make sure it changes two objects at the same time (the "app" user object and the "_users" (CouchDB) user object).

Adding additional fields to the CouchDB user objects in _users doesn't seem to be a problem (see [SO](https://stackoverflow.com/questions/4847145/couchdb-adding-user-profile-attributes-in-user-documents)), so at this point in time I would actually favour removing or merging our `User` Entity class and only use the user objects under _users, also not reinventing the wheel about password changes, etc. 

For that, we do however need the possibility to authenticate users offline through PouchDB. There seem to be pouchdb plugins for this. @liwde should definitely add his opinion here, thinking about the work on our session system.

**Comment by liwde** [comment]
For the new session, getting the user from the local db was pulled out in a separate method to resolve a circular dependency: https://github.com/Aam-Digital/ndb-core/blob/new-session/src/app/session/local-session.ts#L116
From this perspective, I could also load some other entity or data from a completely different source. Is _users in a totally different database in CouchDB or will changes be reflected in our ngo-db database?

I know, this is may be outdated, but: https://github.com/pouchdb-community/pouchdb-authentication/issues/15#issuecomment-63507524
There is this plugin for "seamless authentication", but I have no idea how it is supposed to be working: https://github.com/pouchdb/pouchdb-server/tree/master/packages/node_modules/pouchdb-seamless-auth But as it is organized under some pouchdb-server project, I'd say it might not really be what we want?

One thing I was thinking: There is this notion of design-documents in CouchDB, that can invoke some server logic. Maybe we could have such a document copying changes in _users to the User Entity. Then changing the password would mean, that we explicitly connect a pouchdb-client to the _users database and do our changes there (forcing the user to be online). The design-doc would then make sure this change is reflected in the User Entity synced to the clients for local auth.
I'm not completely sure, if it might work this way. I found, but haven't fully read, this documentation: https://docs.couchdb.org/en/stable/ddocs/ddocs.html#update-functions

**Comment by sleidig** [comment]
Password changes etc. are implemented in another way now.
