### ISSUE TITLE
Improve health tracking with BMI metrics

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#274]
To support the users with making sense of the health data (height, weight), BMI could be calculated and presented in a color-coded way to immediately recognize kids with irregular health stats.

**Comment by sleidig** [comment]
Sample of the excel file including BMI calculation based on Indian standards: [growth_chart_2019_anonymized.xlsx](https://github.com/NGO-DB/ndb-core/files/3204220/growth_chart_2019_anonymized.xlsx)

**Comment by codingfabi** [comment]
implented the basics in PR #337 
I would recommend to merge this branch ASAP, so that the social workers can start working with BMIs. 
I will implement a version that supports coloring later. 

do you have any help on indian bmi standards? in which range is a bmi considerd normal? should we just use who standards?

**Comment by sleidig** [comment]
Great :-)  They mentioned "Indian standards" but I am not sure how that is different. I'd suggest we take WHO as a reference.

The generic `EntitySubrecordComponent` can automatically color code the rows based on the value of the given entities `getWarningLevel()` function, so you just have to implement that function for the HealthCheck entity.

**Comment by codingfabi** [comment]
I implemented WHO Standards. 
After merging the PR, I think this issue can be closed :)

**Comment by sleidig** [comment]
This looks great. Thanks!
