### ISSUE TITLE
Students not visible in SchoolDetailsComponent

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#362]
In the SchoolDetailsComponent the students attending this school should be displayed.
Currently the headers of the table are shown but no students that attend this school.

**Comment by RichardNutt** [comment]
I believe that the problem is that

- in mock-database.ts:162 we apply the filter `filterFun = (e) => e._id.startsWith( ChildSchoolRelation.ENTITY_TYPE) && !e.end && e.schoolId === options.key;`, while e._id looks like `Child:123`. I don't understand what exactly the purpose of this check is and I can't find any documentation!
- in schools.service.ts:42 we call `const child = await this.entityMapper.load<Child>(Child, relation.childId);` with relation.childId which is undefined.

Replacing `relation.childId` by `relation._id` and removing the `e._id.startsWith( ChildSchoolRelation.ENTITY_TYPE)` filter solves this issue, but I don't know if there are any drawbacks to these changes.

**Comment by sleidig** [comment]
This issue also occurs on the live database, so it can't (only) be a problem of MockDatabase.

The filter `filterFun = (e) => e._id.startsWith( ChildSchoolRelation.ENTITY_TYPE) && !e.end && e.schoolId === options.key;` "simulates" the database index that is available on the real database. I'll add some comments - this is far from obvious

**Comment by RichardNutt** [comment]
The problem is that the demo data always contains an end attribute and thus the filter removes all children.

**Comment by christophscheuing** [comment]
Children also currently attend a school, if there is an end date set that lies in the future compared to now. We could easily take this into account by changing
`filterFun = (e) => e._id.startsWith( ChildSchoolRelation.ENTITY_TYPE) && !e.end && e.schoolId === options.key;`
to
`filterFun = (e) => e._id.startsWith( ChildSchoolRelation.ENTITY_TYPE) &&
          (!e.end || e.end >= new Date().setHours(0, 0, 0, 0)) && e.schoolId === options.key;`
in mock-database.ts

That works fine on the local database.

Unfortunately I don't understand how those filters are set for the real database. How is this done?

**Comment by sleidig** [comment]
The couchdb query https://github.com/Aam-Digital/ndb-core/blob/256367a890bdbbf977ad3ace5db65a2aaaa5cb41/src/app/child-dev-project/schools/schools.service.ts#L28 refers to a db index that has to be explicitly created. Unfortunately this specific index is created in the ChildrenService rather than the SchoolsService: https://github.com/Aam-Digital/ndb-core/blob/256367a890bdbbf977ad3ace5db65a2aaaa5cb41/src/app/child-dev-project/children/children.service.ts#L88-L116

Beware, unfortunately this has to be a string containing the javascript function (to prevent the build optimization from messing this up). Refer to the PouchDB guide about how those query functions work: https://pouchdb.com/guides/queries.html

I am including this in my documentation TODO list to be explained and linked further.


I would suggest to refactor SchoolsService: Let's move the `queryRelationsOfSchool` method to the ChildrenService to keep it next to the creation of that db index. We can inject and use ChildrenService within SchoolsService to call that method then.
