### ISSUE TITLE
Search bar is behaving weird

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#366]
**Describe the bug**
The search box (top right) is not working smoothly:
* [x] searching for something into the search box and then deleting it again doesn't reset the result. Previous results remain visible in the dropdown even after clicking somewhere else and clicking back into the empty searchbox.
* [ ] It takes a very long time to load search results (at least on the first search query). A loading animation would be helpful user feedback to signal the status to the user.

**Additional context**
**_Search depends on pouchdb indices so this can only be debugged when setting `useTemporaryDatabase` to false in the config.json_**

**Comment by Lorsbyjm** [comment]
fixed the first point in the pull request by removing a failure in one of the called functions. Furthermore I check the input before sending the query to the database to contain at least a char or a number. Otherwise even an space would be searched and that takes long.
Here, we could also use harder restrictions as a minimum of three letters before going to the database ??

Did not work on the second point yet and the searching is still to long. Animation needed

**Comment by Lorsbyjm** [comment]
@sleidig  For the second problem, the long loading. Instead of using a loading icon  we could add an information block to autolaod alias the search result and display there a text like: "please wait". Furthermore you could display other texts like "please be more specific, there are to many items matching your search" . What do you think? Good idear or too much overhead?

**Comment by sleidig** [comment]
Showing a text to give explanation is a smart idea, especially for the cases when we are not triggering search yet ("Please enter more specific search term, there are too many items matching your search.") and when there are no results ("Sorry, no results are matching your search.").

I didn't completely understand your other suggestion with the alias but "please wait" might stop people while they are still typing, which is not really the intention, is it?

Do you know if the delay is mostly due to preparing result items or the initial search request?

**Comment by tomwwinter** [comment]
The search is now only carried out from three characters upwards.

However, a search like "M Mu" will also trigger a search. Here we should perhaps check whether the first word has at least three characters?

Besides, now:
* The current status of the search is displayed
* The system waits a short time before an entry triggers a search
* An already running search is cancelled (technically only ignored) and replaced with the new search query (switchMap)

**Comment by sleidig** [comment]
> However, a search like "M Mu" will also trigger a search. Here we should perhaps check whether the first word has at least three characters?

I don't see this as a big problem. The goal is to limit the number of results displayed (and loaded - for performance). At least the first goal is still reached.
