### ISSUE TITLE
Increase size of textbox of Note

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#368]
Writing reports is one of the most used features. Users work in the popup Note Details screen, writing often 1-2 paragraphs. The textbox however is currently by default only 2 lines high and doesn't display the full report.

Set a larger default size of the main text box.
Maybe this can be relative to the total screen height to make best use of the available space while still keeping the full form (including the other fields) on the screen without scrolling?

**Comment by vlle1** [comment]
I instead of changed number of rows dynamically used this tag: cdkTextareaAutosize
It basically does the same thing but cleaner (now the text box is exactly as big as the input and there never is another scrollbar, instead the scrollbar of the whole form is used) .
Also I restructured the other points to be in a better logical order and more compact (using fxFlex).
