### ISSUE TITLE
alt text for photos that can't be loaded

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#372]
**Describe the bug**
When a photo file is not available the alt text of the img is display. This is quite long and looks weird in the ChildBlockComponent.

**Comment by NatrixAeria** [comment]
The HTML says
`<img _ngcontent-yiw-c20=""`**`alt="child's photo"`**`class="child-pic-large" src="assets/child.png">`, so I don't get the problem.
Do you mean the text displayed, if the "fallback image" could not be loaded?

**Comment by Lorsbyjm** [comment]
I think the problem is that the text 'child's photo' is to long and just does not look good, because right after it alsways comes the child's name and in the tables, where the block is used, is less space.
The easieast way to solve this, is to remove the alt value, so there will only be the icon for the not loaded image.

Is there a way to disable displaying the image if it is not found?

**Comment by sleidig** [comment]
I am currently looking for a way to avoid the 404 errors when an image doesn't exist as part of cleaning up the new Nextcloud integration for photos (PR #306). The default image as the automatic fallback is normally available even offline through the service workers ... I'll have a look at that again also.
