### ISSUE TITLE
Generalize the edit button of detail forms

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#574]
The edit button for details forms is already used in a lot of components. it would make sense to move it to a general component, so the styling and behavior is consistent.

_Originally posted by @TheSlimvReal in https://github.com/Aam-Digital/ndb-core/pull/560#discussion_r546124392_

**Comment by TheSlimvReal** [comment]
This changes should move the `edit`, `save` and `cancel` button into a single component which provides the input parameter `entity` which is used to determine whether the current user is allowed to use the button as well as two output even emitters to notify about clicks on the `save` and `cancel` button. 
There might be a problem where the `save`  function runs some additional checks before actually saving the entity which eventually can fail. So maybe instead of using output parameters, it might make more sense to pass the function which should be run, once the save button is clicked, into the component.

**Comment by sleidig** [comment]
I think this has become obsolete as the logic is now already centralized in the `EntityFormComponent` that is used everywhere for these kind of forms since PR #817.
