### ISSUE TITLE
Tool-tip responsiveness issue (timeout problematic)

### ISSUE THREAD

**Issue by RichardNutt** [Aam-Digital/ndb-core#590]
Currently tool-tips in the children list appear immediately upon hovering a table entry. Also there is a small delay before they disappear again. I think this should be the other way around. 
If I wanted to see detailed information about something in the table I would want to hover briefly and then get the information displayed instead of this happening immediately. For example; I can't view details about the calendar if I approach it from the top, but I have to move my cursor sideways. Demonstration:
![problem](https://user-images.githubusercontent.com/18560153/103693623-e4abff80-4f99-11eb-9a69-5489d25c6dfe.gif)

Overall it makes navigating the list cumbersome.

**Objective**
Responsive tool-tips

**Proposed Solutions & Alternatives**
Add delay before showing tool-tips. Perhaps that's enough, otherwise it might be worth a try to remove the delay before hiding them.

**Comment by sleidig** [comment]
If I remember correctly, we added the delay before hiding tooltips to allow users moving "into" the tooltip with the mouse (e.g. to select some text inside the tooltip box). Otherwise it may happen that on your way on to the tooltip you leave the active area and the tooltip disappears before you can reach it.

Your issue is absolutely valid though. I think adding a delay before showing tooltips is a good idea
