### ISSUE TITLE
Avoid uploading the whole image in CI to report code coverage

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#610]
At the moment CI is uploading a large image (e.g. https://github.com/Aam-Digital/ndb-core/runs/1734572526?check_suite_focus=true#step:4:2776 ) because the code coverage file is needed in a separate job. There should be some way to upload just the code coverage file and save time in the CI (especially as it sometimes crashes on this step)

Maybe artifacts? https://stackoverflow.com/a/57877438/1473411

**Comment by sleidig** [comment]
Maybe it could be achieved by splitting the building (in Dockerfile) and the testing (by using the previously built image)?
and use the aamdigital image as the github action image for the test step, uploading the coverage file as an artifact, @TheSlimvReal ?

**Comment by TheSlimvReal** [comment]
Some thoughts on that:
- Currently we build the image with buildx, which allows to cache and upload the image automatically
- We could use the image as base a for the GitHub Workflow ([see here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer))
- In this case, the GitHub cache could be used to store the `node_modules` folder
- However, I dont think we will be able to upload the image (to DockerHub) at the end of the run if we are inside the image itself 

Currently we need the `.coverage` and the `dist` folder that is created in the Docker image. The first one to upload it to CodeClimate, the latter one to create a `.tar` for the GitHub release. This approach could be changed to be run completely in Docker:
- Upload coverage inside the image. This approach requires to install some additional dependencies inside the image and extract and pass some required arguments into the image in order for the coverage reporter to work.
- The release of the `dist` folder on GitHub is not required due to the release on DockerHub, the GitHub releases could just be used for the history of changes.

This approach would make the Docker image a bit more complex, but the additional dependencies would not impact the final image. The GitHub Workflow would then only consists of one step where the Image is built, but this step would have to pass a lot of arguments into the image.
I dont consider this problem very high priority, because the workflows dont have any problems if no changes to the `package.json` or the `package-lock.json` occur. If changes happen, these changes should be done in a separate branch and commited and merged into all other branches as fast as possible.
