### ISSUE TITLE
Add labels to the entities (for different language versions)

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#886]
Right now, there's no separate label for entities like "Child" or "School". E.g. when trying to delete a child from the child details view, the message "Are you sure you want to delete this Child ?" is shown, where "Child" is taken directly from the entity type.  It is not read from the configuration and at the current state it is not possible to add different language versions for this label.

One problem might be that the entity name is also relevant for the URL, so care should be taken when adding the label feature.

_**also see #1056 **_

**Comment by sleidig** [comment]
we have an alias table to rename the entity types (e.g. from "School" to "Team") already (see https://github.com/Aam-Digital/ndb-core/blob/master/src/app/core/entity-components/entity-details/entity-details.component.ts) but that is not feasible to also handle translations. We should replace that existing approach.

The best way to handle this is probably to have a `label` property for the entity config, so that any instance can just rename that just like menu items are renamed (in [config-fix](https://github.com/Aam-Digital/ndb-core/blob/master/src/app/core/config/config-fix.ts)).

**Comment by sleidig** [comment]
This is related to #1056 (defining entities completely via config without a typescript class) insofar as that other issue would supersede this and already cover the label as well. It could still make sense to first implement this simpler improvement, however.
