### ISSUE TITLE
Filters should not be case sensitive and ignore spaces

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#893]
**Describe the bug**
When creating a filter on a string property, a filter button is created for each existing value of this property. This means that in case the values are 'one value', ' one value ', and 'One Value', three filter buttons will be created. This is very confusing for the user. Instead, there should only be one of the options which will include all other options. E.g. a filter button with 'One Value' is available and will also list the values 'one value' and ' one value '. This can be achieved by ignoring the case and the spaces when creating the filter values. Which label is used for the filter (e.g. 'one value', ' one value ' or 'One Value') can be selected randomly.

**Comment by sleidig** [comment]
This suggestion can only mitigate parts of the problem. I have also seen typos and different spellings by users in such fields, which we cannot automatically resolve. The more thorough and explicit solution would be to use configurable-enum (i.e. fixed dropdown lists) for such properties. Otherwise we have some hidden magic that does not apply to all workflows (e.g. in exports and maybe at other times when we process the data there are still distinctions).

If dynamically adding new fields is necessary, maybe we should think of a form field component that offers existing values as autocomplete but allows any kind of new input?

**Comment by TheSlimvReal** [comment]
Yes that are good points. So either we push to create a feature that actually lets users add new fields to configurable enums (should actually be quite straight forward to implement) or provide the input field with hints for other existing values (which is also very interesting in terms of removing duplicates in general) but I guess the later option is rather complex to implement.

**Comment by sleidig** [comment]
with the editable configurable-enum dropdowns, this is probably not a major issue anymore.
