### ISSUE TITLE
Cleanup UI when adding new school

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#894]
In the view of adding a new school the various entry fields look a bit disordered:

<img width="1272" alt="Bildschirmfoto 2021-07-17 um 12 53 15" src="https://user-images.githubusercontent.com/47225324/126034677-fc1ca175-b96e-4306-a7fd-195431dcc0e5.png">

Maybe a little cleanup of the UI in this component might enhance the user experience.

**Comment by sleidig** [comment]
This is a good suggestion, I would also remove some fields from the "School" entity to simplify things:

- name: string
- privateSchool: boolean
- medium: string **--> rename "medium" to "language"**
- address: string 
- phone: string
- timing: string
- remarks: string
- ~website: string~ **--> remove**
- ~upToClass: number~ **--> remove**
- ~academicBoard: string~ **--> remove**
- ~workingDays: string~ **--> remove**

TODOs for this:
- [ ] change config-fix.ts: "view:school/:id" form fields, "view:school" columns
- [ ] change config-fix.ts: add all the properties to "entity:School" (see "entity:Child" as example)
- [ ] change school.ts: remove all properties except "name" (that way, any customer can change these properties through the config and we have less details in our code base, which is just confusing)
- [ ] fix "DemoSchoolGenerator" service: after removing the properties from the "School" class, the demo data has to use `school["address"] = ..."` instead of `school.address = ` to avoid error messages
