### ISSUE TITLE
Readonly function columns in EntitySubrecord lists do not update

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#919]
**Describe the bug**
Values of ReadonlyFunctions are not updated when a row in the table is edited and saved.

**To Reproduce**
1. Go to Child Details, Health section
2. Edit a Height & Weight row, changing the height and save it
3. The background color may be updated if the resulting BMI changed a lot but the "BMI" column of the table is still showing the old number even after saving.

**Expected behavior**
BMI field should update at least after the change has been saved.

**Additional context**
Component: ReadonlyFunctionComponent
Problem: entity-subrecord.component.html keeps the view because no edit is defined for ReadonlyFunction, therefore no recreation of the component takes place.

**Comment by TheSlimvReal** [comment]
The effect only appears in inline editing, not when editing through the popup. The readonly functions only updates, if the entity object is newly assigned to avoid change cycles. Probably the save function for inline editing has to be adapted to properly assign the row correctly rather than just updating the inner values.

**Comment by sleidig** [comment]
confirmed, this has been fixed
