### ISSUE TITLE
config.json requested at en-US (i18n) sub-path

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#926]
the normal config.json file is not loaded anymore because requests go to the subpath of the internationalization url (en-US/assets/config.json). Similar problems are likely for the child-photos.

for example see https://dev.aam-digital.com/de/

**Comment by sleidig** [comment]
Probably we should have only one central assets folder for all languages. For example users do not want to upload separate passphotos for each UI translation

**Comment by TheSlimvReal** [comment]
The problem also makes the app think its in demo mode and therefore changing passwords is not possible

**Comment by TheSlimvReal** [comment]
By default, angular automatically copies the contents of the assets folder into the assets folder of each locale, so far so good.
The problem is, that we manually map the `config.json` file into the assets folder **after** the build process.

So there are two options:
1. Manually map the config file (and potentially child photos) into the folder of each locale
2. Add a rule to the `default.con` of nginx which redirects all requests to `*/assets/config.json` (and also `*/assets/child-photos/`) to the base assets folder. With a little more nginx skills we could also first check if the file exists in the assets folder of the locale and if not redirect it to the general assets folder.

I vote in favor of the second option as it means a cleaner `docker-compose.yaml` file.
