### ISSUE TITLE
Improve UX of "Add Child" in school details view

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#982]
A few aspects about the form to add a child to a school from the school details view could still be polished further:

- The child select does not open a dropdown when clicking into it, only when starting to type (in other forms this is opening, e.g. RecurringActivity details to add participants)
- The purpose of "From" and "To" fields has often been unclear to users, we should add tooltip explanations.
- Can we use the same component in the school details that we use in the child details, also offering to remove a child, etc.?
- Is there a way to label to button more generically (for some customers we talk of "participants" instead of children), maybe related to #886

**Comment by TheSlimvReal** [comment]
Regarding the button: The name can be changed by providing a different label for the `childId` property of the `ChildSchoolRelation` entity.

**Comment by TheSlimvReal** [comment]
Regarding the deleting: We can't use the basic logic of the `EntitySubrecord` there because currently we are actually displaying the children, not the `ChildSchoolRelation` objects, which means the delete button would delete the child and not just the child's participation at the school. To make a more similar look and feel to the component in the child details view, we could instead display the `ChildSchoolRelation`, which would then only show the `ChildBlockComponent` (not the age as a additional column), but it would allow to use all the default behavior of the `EntitySubrecordComponent` (creating , editing, deleting out of the box).
Otherwise we would need to make the delete behavior _overwritable_

**Comment by sleidig** [comment]
True. I think for logical consistence doing it the same way as in the PreviousSchoolsComponent in the Child Details would make sense (i.e. displaying the school block and ChildSchoolRelation infos)

**Comment by TheSlimvReal** [comment]
- [ ] Select single entity should automatically open the dropdown when selected
- [ ] Add description for from and to button e.g. _Date at which the child started at the school_
- [ ] Make the `ChildrenOverviewComponent` more similar to the `PreviousSchoolsComponent`. It should display the columns `childId`, `schoolClass`, `start`, `end`, `result` and the `Add Child` button should be removed and instead the `add` button from the `EntitySubrecord` should be used.
